# Generated by Django 5.0.2 on 2024-02-28 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_kr', models.CharField(max_length=100, verbose_name='Имя и Фамилия Клас.рук')),
                ('email_kr', models.EmailField(max_length=254, verbose_name='Email Клас.рук')),
                ('number_kr', models.CharField(max_length=15, verbose_name='Номер Клас.рук')),
            ],
            options={
                'verbose_name_plural': 'Классный рук',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name_par', models.CharField(max_length=100, verbose_name='Имя и Фамилия')),
                ('email_par', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_par', models.CharField(max_length=15, verbose_name='Номер')),
                ('class_num', models.CharField(max_length=5, verbose_name='Класс')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='Profile.teacher', verbose_name='Учитель')),
            ],
        ),
    ]
